### ISSUE TITLE
Mecool KII PRO DVB

### ISSUE THREAD

**Issue by j3dd4h** [dtechsrv/LibreELEC-AML#11]
Which dtb file should be use for Mecool KII PRO (DVB) ?
Using the default one,  LAN & DVB  is not working properly.
dvbv5-zap showing all packet are null (pid 8191)

_Using LNBf UNIVERSAL
	Universal, Europe
	Freqs     : 10800 to 11800 MHz, LO: 9750 MHz
	Freqs     : 11600 to 12700 MHz, LO: 10600 MHz
using demux 'dvb0.demux0'
reading channels from file 'channel.conf'
tuning to 11861000 Hz
       (0x00) Signal= -37.22dBm C/N= 12.54dB
Lock   (0x1f) Signal= -37.42dBm C/N= 12.41dB
	  Layer A: Signal= 89.00% C/N= 62.06%
  dvb_set_pesfilter to `0x2000`

 PID          FREQ         SPEED       TOTAL
1fff  23434.83 p/s  34419.9 Kbps     4324 KB
TOT   23434.83 p/s  34419.9 Kbps     4324 KB

Lock   (0x1f) Signal= -37.34dBm C/N= 12.50dB
	  Layer A: Signal= 89.00% C/N= 62.56%_

**Comment by dtechsrv** [comment]
It doesn’t irrelevant which variant you have from KII Pro.

If your device is an original S905-based (GXBB), this dtb is required:
http://libreelec.dtech.hu/device_trees/S905/gxbb_p200_k2_pro.dtb
... but, if it is a newer S905D-based (GXL), this dtb is required for that:
http://libreelec.dtech.hu/device_trees/S905D/gxl_p231_2g_dvb.dtb

Unfortunately, I can't help with the deeper errors related to DVB.
First you need to try the `dvb-latest` or `crazycat` driver package.

**Comment by dtechsrv** [comment]
Did it work?

**Comment by dtechsrv** [comment]
Don't get mad, I will close this issue.
If there is no answer for two weeks, then what I suggested is either working or no longer interesting to you.

Whatever the case, I can’t help you further with this topic.
