### ISSUE TITLE
Adding support for php7 and chromium-browser on libreelec

### ISSUE THREAD

**Issue by suyog44** [dtechsrv/LibreELEC-AML#16]
Hi @dtechsrv ,

I am willing to run php based website on localhost, but i wont able to see php support in existing  package. How i can add the php support. Also wants to know how to add chromium-browser (might be chromium-browser deb will help). OR instead of chromium , i can write pythons script which act as a browser to display the website (like kiosk).

Best Regards,                 
B Suyog

**Comment by suyog44** [comment]
Hi @dtechsrv  

I am using Tanix TX3 Mini (Amlogic S905W 1G RAM 8G Nand Flash, sv6051 wifi). Currently i am working on ARMBIAN, unfortunately not able to run splashscreen (plymouth) and Wifi is not working.

Thats Why i found libreelec quite interesting, because its supports WiFi , Screen Resolution Setting quite easy to handle, Simple Interface. Only thing i was trying to add is my KIOSK application on Home page.

**Comment by dtechsrv** [comment]
I think you should look for an older version, which is still based on the 3.14 kernel.
