### ISSUE TITLE
NOT an issue, but compliment!

### ISSUE THREAD

**Issue by 73-de-LZ** [dtechsrv/LibreELEC-AML#17]
Firs of all Thank You Dear Dtech! Ultra fine job!
I was testing LibreELEC-HD18Q.arm-9.2.8.6.img last night on my very old S805 hardware and it is working great, WiFi also, not observed a single issue! Since i am new to this things i want to ask something, on which Linux kernel is based this release? In fact i want to know everything about how it is made, how you get to here? Ofcourse it is matter of lot of knowleges, but with few words, the most important.  I dont want to consume much of your time, if there was a book by you, answering my question, i would read it with pleasure.
Thanks and wish you good luck!

**Comment by dtechsrv** [comment]
Hi @73-de-LZ!

It is still based on the old 3.10 kernel. However, since Kodi 19 amcodec support is no longer available, so this version is the last one that can be used with this kernel. It is not certain that it makes sense to delve into the development of this version from this point now.
