### ISSUE TITLE
RTL8153 Gigabit Ethernet Adapter not working with 9.2.8.7 (HD18Q.arm)

### ISSUE THREAD

**Issue by MyKeySoftMK** [dtechsrv/LibreELEC-AML#21]
I have an "old" MK808b and installed LE with your images. WLAN is working fine, but the USB-LAN is not working. 

`LibreELEC (dtech): 9.2.8.7 (HD18Q.arm)
LibreELEC:~ # lsusb
Bus 001 Device 002: ID 046d:c016 Logitech, Inc. Optical Wheel Mouse
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 003: ID 0bda:8153 Realtek Semiconductor Corp. RTL8153 Gigabit Ethernet Adapter
Bus 002 Device 002: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`

How can i enable it?

**Comment by dtechsrv** [comment]
The v3.10 kernel does not yet include support for the Realtek RTL8153 USB3.0 Ethernet.

Related file in kernel: https://github.com/kszaq/linux/blob/amlogic-3.10.y/drivers/net/usb/r8152.c

The kernel we use includes driver version v1.0.0 (2013/05/03), the minimum required version is v1.03.0 (2013/12/26) which should support RTL8153. I'm looking into the possibility of a simple driver update, please be patient.

**Comment by dtechsrv** [comment]
I added a PR with the updated driver: https://github.com/dtechsrv/LibreELEC-AML/pull/22.
