### ISSUE TITLE
Chromium on MK808B (S805) with LibreELEC

### ISSUE THREAD

**Issue by MyKeySoftMK** [dtechsrv/LibreELEC-AML#23]
Hello,

i want a Webbrowser on the MK808. I have try to install the chromium addin for Kodi, but i did´t find them in the repositories.

My goal is: MK808 with a working Wifi and a UI-Linux (like Mate or newer) with a browser. When the MK808 starts it should open a website to showing a local website (We need it for our video studio)

Your LibreELEC works fine (the Wifi). I have try it with "ubuntu-mate-15-04-s805-standard-0_95_Beta.img.xz" but the Wifi is not working. We need Wifi for Sync with NTP

Do you know a Idea how i can reach the goal? Maybee with Kodi or without Kodi?

**Comment by dtechsrv** [comment]
#16 
> Chrome: Unfortunately, it needs X11 to run, so it will never run under LE on ARM, it only works under x86.
