### ISSUE TITLE
Update Plugin minsatip in the addons ???

### ISSUE THREAD

**Issue by dnmnhat** [dtechsrv/LibreELEC-AML#26]
I'm using Libreelec on a Mecool Kiii Pro with the version for Amlogic S912 you're building.
I use the minisatip addons plugin but it's been a while since it's been updated, can you update the minisatip addons???
I have tried minisatip docker but it can't be used stably (I have trouble configuring ip network in docker )
For TVheadend I have it configured as satip-server, but for a new user like me, it's not successful to use tvheadend on libreelec as satip-server to connect to Tvheadend on Synology.

**Comment by dtechsrv** [comment]
Sorry for the late answer. I'll check the dependencies and try to make a newer version package for testing. I ask you to be patient.

**Comment by dtechsrv** [comment]
Here is a test version for Amlogic S905x/S912, based on the source of yesterday's last version ([v1.2.83](https://github.com/catalinii/minisatip/releases/tag/v1.2.83)):
[service.minisatip-9.2.0.102.zip](https://github.com/dtechsrv/LibreELEC-AML/files/11624316/service.minisatip-9.2.0.102.zip)

Please test it and let me know if it works properly.
If it works, it will be added to the main repo, but if it doesn't, we will look for the cause of the error. Thanks.

**Comment by dnmnhat** [comment]
I have installed and used it, and found that minisatip has fully recognized the DVB tuner of Mecool KIII Pro, and I set up scanning for DVBT2 and DVBC frequencies, then I can use it to play channels.
Unfortunately I don't have a pan + LNB device to scan DVBS satellite frequencies so I can't tell if DVBS is working or not?
Sorry I don't know how to extract the minisatip log so you can look more specific

**Comment by dtechsrv** [comment]
Thank you for the feedback. Unfortunately, I don't have satellite units either, but I don't think there will be a problem with that.

So I will include it into the repo, but the old version will also remain there, so if someone has a problem, they can switch back.

**Comment by dtechsrv** [comment]
[minisatip: update to 1.2.83 and addon (102)](https://github.com/dtechsrv/LibreELEC-AML/commit/1506022a308bfdac4a007cb150d8c2aeba965485)
