### ISSUE TITLE
USB Nano Bluetooth 5.0 TP-Link UB500 or USB Bluetooth 5.0 Orico BTA-508 ????

### ISSUE THREAD

**Issue by dnmnhat** [dtechsrv/LibreELEC-AML#29]
I'm using Libreelec on a Mecool Kiii Pro with the version for the Amlogic S912 you're building.
Because my KIII Pro mainboard broke the wifi + bluetooth module.
  I bought TPlink's USB Bluetooth (USB Nano Bluetooth 5.0 TP-Link UB500) and USB Bluetooth from Orico (USB Bluetooth 5.0 Orico BTA-508).
But it cannot be used with the Libreelec you build.
Can you add the driver? Or can you suggest me which Bluetooth USB dongle should I buy that is supported?
Thanks !

**Comment by dtechsrv** [comment]
My investigation revealed that both dongles contain a Realtek RTL8761B chip.

Unfortunately, an independent Realtek BT stack was not yet available under the 3.x kernels, so it is not possible to easily add a new one without jeopardizing the functionality of the existing rtl_bt solutions "hacked in" earlier by other developers.

So at the moment I can't recommend any external BT dongle, but even if I could, it would definitely not use the bluetooth 5.0 protocol.

**Comment by dtechsrv** [comment]
I am working on the backport of the `bt_rtl` driver, so it is possible that support for the devices you use will still be added.

**Comment by dtechsrv** [comment]
Mecool KIII Pro + TP-Link UB500 -> It works perfectly with the latest snapshot image:
https://libreelec.dtech.hu/snapshots/20241229_master_13fc1c8/

![KII-Pro+TP-Link-UB500](https://github.com/user-attachments/assets/ed9da207-92bc-4f44-b5e4-7dcb9b6f5d4a)

If you could try it with your Orico stick, I would appreciate it.

**Comment by dtechsrv** [comment]
In the meantime, I investigated a bit and the Orico 508 stick has a different USB ID (0bda:8771) and needs a different firmware (rtl_bt/rtl8761bu_fw.bin), so unfortunately it won't work with this kernel driver.

However, this has only been added in a kernel driver that simply cannot be backported to 3.10/3.14, so I dare not promise that I can solve this at all.

_In any case, the TP-Link UB500 fortunately works flawlessly even on Meson8* (S8xx) devices with the currently applied `btrtl` driver._

**Comment by dnmnhat** [comment]
I have both types of usb above, I don't have time to test with the new build yet. I looked in the new build folder, there is no update for s912 but I'm too busy to install new, can you create an update for s912?

**Comment by dtechsrv** [comment]
> I looked in the new build folder, there is no update for s912 but I'm too busy to install new, can you create an update for s912?

But they are not missing, here are the images for the S912:

![snapshots-s912](https://github.com/user-attachments/assets/9bb3f8fb-4466-4131-9570-ab394ee002cb)

**Comment by dnmnhat** [comment]
Thanks, I will try it as soon as I can

**Comment by dtechsrv** [comment]
> Thanks, I will try it as soon as I can

You don't necessarily have to test it this year, you can do it in 2025 as well. Happy New Year! :)

**Comment by dtechsrv** [comment]
The final v9.2.8.16 was released yesterday, so you don't need to install a snapshot version. If the automatic update is enabled on your box, the update will be downloaded after startup.

**Comment by dnmnhat** [comment]
I have updated and used both usb types that I have (Orico and TP-link). They work perfectly without any problem.
