### ISSUE TITLE
LibreELEC-HD18Q.arm-9.2.8.7.img.gz and 720p 50Hz

### ISSUE THREAD

**Issue by MyKeySoftMK** [dtechsrv/LibreELEC-AML#31]
I want to use my MK808B Plus to use as a LEDI Clock in my Video-Studio. The External HDMI-Input of my Mixer Device has a "720p 50Hz" Requirement.

How can I config the 9.2.8.7 to run in this mode/resolution?

BTW: After installing LibreELEC i install  Debian Xenial (16.04) mit MATE for the UI. In the configuration is put in the 720 mode - but the mixer didn´t show the picture from my MK808B

**Comment by dtechsrv** [comment]
If you only use it for this purpose and you don't need any other resolution at all, it is best to use a static `disp_cap` file to override the allowed resolutions and place it in `/storage/.kodi/userdata` with the following content:
`720p50hz`

**Comment by MyKeySoftMK** [comment]
Where i find the file? On the SD-Card I didnt find this mentioned folder/file.

I have a "hdmi.sh" - but only they mentioned mode "720p" but not the 50Hz.

all the other files are binaries - so i didn´t can change them easy

I need the MK808 only for this purpose in future with 720p 50Hz

**Comment by dtechsrv** [comment]
This file does not exist by default, you have to create it like this:
`echo "720p50hz" > /storage/.kodi/userdata/disp_cap`

**Comment by dtechsrv** [comment]
Did it work? Because then I would close this ticket.

**Comment by MyKeySoftMK** [comment]
> Did it work? Because then I would close this ticket.

No - sorry - i have tried sometimes - but they still have the 60Hz - but i need the 50Hz

**Comment by dtechsrv** [comment]
I just can't imagine this solution not working for you. I just tried it on an S805 MXQ box.

I didn't do anything special, I just ran that one single line:
`echo "720p50hz" > /storage/.kodi/userdata/disp_cap`

After a restart, it was not possible to choose another resolution, it appeared immediately with this resolution.

See attached photo:
![disp_cap_720p50Hz](https://github.com/dtechsrv/LibreELEC-AML/assets/49231904/56db6e23-0c30-4618-9807-0a2f947cef58)

**Comment by dtechsrv** [comment]
You are not a very talkative person.
I always feel like I'm using a corkscrew to pry the answer out of you, and a week or two goes by in the meantime. :(

Anyway, the solution I presented above works, that's a fact.
So I ask you directly: "Are you sure you did the same?"

**Comment by dtechsrv** [comment]
Well, under Linux Mint there is probably no `/storage` directory, it is specifically used by LibreELEC, because the `/dev/data` partition is mounted there.

Unfortunately, I cannot help under other distros, but the above solution should work under LibreELEC.

If you don't mind, I'll close this ticket now.
