### ISSUE TITLE
Analog output on Minix X8-H

### ISSUE THREAD

**Issue by kedar-1** [dtechsrv/LibreELEC-AML#34]
Hello,

**thanks for your effort to let the Amlogic devices "live".**

I'll build a VU meter for music using Arduino.
As the input will be based on Analog stereo module I need an Analog output from my Minix box.
But Analog is not working - ALSA: M8AUDIO, Analog selected.

Is it issue with Minix X8-H systems or is it only my issue?

Last week I've purchased a SPD/IF to Analog converter as Digital output works as expected so I have workaroud to be able to build VU meter... But working Analog output will be plus.

Thanks

Radek

**Comment by dtechsrv** [comment]
Unfortunately, I don't have such a device at all, so I can't dig deep into the problem. According to dtb's audio section, it contains an ES8323 audio codec, but unfortunately I don't know more about that either.

All the hardware and kernel work is one-on-one @datrh's work, but it looks like he has investigated this issue before, but was unable to resolve it:
https://forum.libreelec.tv/thread/12155-libreelec-9-0-kodi-18-x-for-minix-x8-x8h-x8h/?postID=135146#post135146

**Comment by kedar-1** [comment]
Thanks for a quick answer.

I'll be ready to test if needed.
I'll try to look to the kernel...

R.

**Comment by dtechsrv** [comment]
I can't find any errors in the DTB, and I have no idea how to set the correct ALSA config without knowing this codec.
I'm sorry, but I can't help you with that.
