### ISSUE TITLE
installtointernal

### ISSUE THREAD

**Issue by 73-de-LZ** [dtechsrv/LibreELEC-AML#35]
Hello, thanks for good work and the images!
I am using LibreELEC-HD18Q.arm-9.2.8.13 on SD card and everything is working well, but when I try to move it to the flash with installtointernal give me -sh not found.
Tried install2emmc and also does nothing, what I have missed?

**Comment by dtechsrv** [comment]
`install2emmc` -> Script with that name does not exist in my images.
`installtointernal` -> Are you sure you typed it right?

Try this way:
`/usr/sbin/installtointernal`

**Comment by 73-de-LZ** [comment]
Already killed that "NEW" box with OLD HW inside with another armbian image. 
Your image was the only one ever and everywhere found to be working with WiFi and everything. Box is MXQ PRO 4K 5g, bought for 15EU from Aliexpress and supposed to be S905X as in the listing and on the label, but inside is turned to be S805 , what a fraud... Unfortunately I can't find working Android image for USB_Burning_Tool and i can't test it anymore, RIP ...

Thank you for your wonderful job, I am sure lot of people are very happy to see the resurrection of those old HW thanks to your work, amazing!

**Comment by dtechsrv** [comment]
I have a flashdump from mine, if you want I will upload it and send you a link, so you can use it to restore your box.

Can you send me an inside photo from your box? I can make sure that your motherboard PCB is the same as mine.

**Comment by 73-de-LZ** [comment]
[MXQ_S805.zip](https://github.com/dtechsrv/LibreELEC-AML/files/14057761/MXQ_S805.zip)
Thank you very much, i didn't wanted to bother you, but i feel kind of a love to these devices, as in fact one TV box exactly with S805 spark me and had opened this whole new world for me. I have original firmware for those old box, but it is OTA update and there are some difference between them, at least WiFi. Both of them working/worked with your images, even the old one was with LibreELEC-HD18Q.arm-9.2.8.6.img and updated now with LibreELEC-HD18Q.arm-9.2.8.13.img with /opt folder inroot, but not moved yet to the internal memory. I am afraid the MXQ will be hard to be resurrected without flashable image as now there is not even recovery, and while i tried few flashabale images with different versions of USB_Burning_Tool it always give me the same error after finishing boot. The only thing i didnt tried is to find the testpoint to connect it in boot ROM mode, but will do that now. 

[MXQ_S805.zip](https://github.com/dtechsrv/LibreELEC-AML/files/14057761/MXQ_S805.zip)

**Comment by dtechsrv** [comment]
This is exactly the same as what I have. I made a recovery image from the flashdump, but it doesn't work with USB Burning tool, only from SD card:
[https://libreelec.dtech.hu/_TEST_/MXQ2022_S805_RTL8723AS_Restore.zip](https://libreelec.dtech.hu/_TEST_/MXQ2022_S805_RTL8723AS_Restore.zip)

Please extract and follow the instructions in the `README.TXT`.

**Comment by 73-de-LZ** [comment]
Yuhuuuuu, the magic happened, may God bless You!
Now i know exactly what they mean with that logo, was almost forgot it, but after your help it becomes even more colorful!
![20240126_222621](https://github.com/dtechsrv/LibreELEC-AML/assets/16052106/83b1c1e3-35d3-4770-b32e-c609c00176de)
Thank you very much, it was not about the box, nor for the money, but a matter of honor to make things works, so the honor is entirely your! Have a nice weekend dear master!
