### ISSUE TITLE
docker ??

### ISSUE THREAD

**Issue by bellad17** [dtechsrv/LibreELEC-AML#36]
hello , i have put LibreELEC-Generic_S805.arm-9.2.8.14.img.gz on my box tv , it's good 
but in add on i cannot see docker
i see on github packages/addons/repository/repository.linuxserver.docker
i not understand
thank you

**Comment by dtechsrv** [comment]
Docker never worked under builds based on the amlogic 3.10 kernel.

https://forum.libreelec.tv/thread/23456-legacy-v9-2-lts-builds-for-amlogic-s805-s8x2-s905-s912-and-all-wetek-boxes/?postID=176289#post176289

**Comment by dtechsrv** [comment]
If you are still interested, there will be some developments regarding docker soon.

A little spoiler:
![docker-test-on-amlogic-s8xx](https://github.com/user-attachments/assets/fb5e6d25-5b82-47e2-99b9-5238223fd4ee)
