### ISSUE TITLE
tvheadend

### ISSUE THREAD

**Issue by jose197105** [dtechsrv/LibreELEC-AML#7]
is it possible to compile latest tvheadend server to work with this build.  I  am using wetekplay 1.

thanks

**Comment by dtechsrv** [comment]
There is no newer version from branch 4.2 (last: v4.2.8), and branch 4.3 is not yet stable.
Is there any feature that would justify a newer version because it doesn't work under the current version?

**Comment by dtechsrv** [comment]
https://forum.libreelec.tv/thread/3416-tvheadend-nightly-builds-for-le/?postID=163371#post163371
