### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by BlackGlassSkin** [dtechsrv/LibreELEC-AML#8]
Hi. thasks for your works

Could you please do Docker support for amlogic s812

**Comment by dtechsrv** [comment]
Hi @BlackGlassSkin,

Unfortunately, you are not the first to find me on this topic, please read my previous answers on this:
https://forum.libreelec.tv/thread/23456-le-9-2-x-build-for-some-amlogic-s905-s812-and-s805-devices/?postID=160299#post160299
https://forum.libreelec.tv/thread/23456-le-9-2-x-build-for-some-amlogic-s905-s812-and-s805-devices/?postID=160337#post160337

**Comment by BlackGlassSkin** [comment]
thanks,
