### ISSUE TITLE
I would like to know how do I make a tar.gz file from a specific folder

### ISSUE THREAD

**Issue by tobenary** [dtechsrv/LibreELEC-AML#9]
I haven't seen this process in the readme file.

For example, I have this box:

https://github.com/dtechsrv/LibreELEC-AML/blob/master/build_3rdParty.sh
# MXIII Plus / G
# Specs: Amlogic S812 SoC, 2 GB RAM, Gigabit LAN, AP6234 WiFi
PROJECT=S8X2 DEVICE=MXIII-Plus ARCH=arm make image -j8

So I'm navigating to https://github.com/dtechsrv/LibreELEC-AML/tree/master/projects/S8X2 and I find folders and files, but not the tar.gz file.

I also find by google search this link:
https://disk.yandex.ru/d/8vNYuuxynz1L0w/20210505-s8xx?w=1
Is it what I need to use, or is there a new file?

**Comment by dtechsrv** [comment]
http://libreelec.dtech.hu/3rdParty/S8X2/MXIII-Plus-S812_2G-AP6234/

**Comment by dtechsrv** [comment]
Did I manage to answer your question?

**Comment by tobenary** [comment]
Yes, thank you very much!
